apiVersion: v1
kind: Pod
metadata:
  name: volume-cm-example-pod
  labels:
    type: volumeCmExample
spec:
  volumes:
    - name:  vol-from-cm
      configMap:
        name: first-configmap
  containers:
  - name: container1
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
    volumeMounts:
      - name:  vol-from-cm
        mountPath: /etc/config
  # - name: container2
  #   image:  alpine
  #   resources:
  #     limits:
  #       memory: "128Mi"
  #       cpu: "500m"
  #   ports:
  #     - containerPort: 8080
  #   volumeMounts:
  #     - name:  vol1
  #       mountPath: /volData2