apiVersion: v1
kind: Pod
metadata:
  name: volume-example-pod
  labels:
    type: volumeExample
spec:
  volumes:
    - name:  vol1
      emptyDir: {}  
  containers:
  - name: container1
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
    volumeMounts:
      - name:  vol1
        mountPath: /volData
  # - name: container2
  #   image:  alpine
  #   resources:
  #     limits:
  #       memory: "128Mi"
  #       cpu: "500m"
  #   ports:
  #     - containerPort: 8080
  #   volumeMounts:
  #     - name:  vol1
  #       mountPath: /volData2