apiVersion: apps/v1
kind: Deployment
metadata:
  name: first-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: deploy-app
  template:
    metadata:
      labels:
        name: deploy-pod
        app: deploy-app
    spec:
      containers:
      - name: helloworld
        image: aamirpinger/helloworld
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "256Mi"  # Set your desired memory limit
            cpu: "200m"      # Set your desired CPU limit
          requests:
            memory: "128Mi"  # Set your desired memory request
            cpu: "100m"



