kind: Pod
apiVersion: v1
metadata:
  name: pod-with-secret
spec:
  containers:
    - name: container-with-secret
      image: nginx
      envFrom:
        - secretRef:
            name : secret-cli
      resources:
        limits:
          memory: "256Mi"  # Set your desired memory limit
          cpu: "200m"      # Set your desired CPU limit
        requests:
          memory: "128Mi"  # Set your desired memory request
          cpu: "100m" 